import { Pricing } from "@/types";

export const pricing: Pricing[] = [
  {
    id: 1,
    service: "web",
    headingSmall: "Launch Faster",
    headingLarge: "One Page Website",
    paragraph:
      "Perfect for new businesses, startups and local service providers looking to establish a professional online presence without the cost of a larger website.",
    priceLarge: "£495",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£24",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 2,
    service: "web",
    headingSmall: "Grow Online",
    headingLarge: "Multi-Page Website",
    paragraph:
      "Designed for businesses that mean business. Our multi-page websites provide the flexibility to showcase your services, build trust with potential customers and create a stronger foundation for long-term growth.",
    priceLarge: "£1250",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£40",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "2-6 pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 3,
    service: "web",
    headingSmall: "Scale Further",
    headingLarge: "Growth Website",
    paragraph:
      "Designed for businesses that need more content, more services, more locations & more room to grow. Ideal for established businesses looking to improve visibility, expand into new areas or create a stronger online presence.",
    priceLarge: "£2500",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£70",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "7+ pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 4,
    service: "web",
    headingSmall: "Build Authority",
    headingLarge: "Blog & Insights",
    paragraph:
      "Add a fully managed blog section to your website and publish content that helps build trust, improve search visibility and demonstrate your expertise over time.",
    priceLarge: "£30",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Why it matters",
    bulletList: [
      "Improves search visibility",
      "Builds trust with potential customers",
      "Demonstrates your expertise",
      "Targets valuable local search terms",
      "Supports long-term SEO growth",
    ],
    badge: true,
    badgeText: "Popular Upgrade",
  },
  {
    id: 5,
    service: "brand",
    headingSmall: "Get Recognised",
    headingLarge: "Logo Design",
    paragraph:
      "Perfect for new businesses looking for a professional logo that can be used across digital and print applications.",
    priceLarge: "£300",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Primary logo",
      "Logo icon / mark",
      "Light and dark versions",
      "PNG exports",
      "Vector artwork",
    ],
    badge: false,
  },
  {
    id: 6,
    service: "brand",
    headingSmall: "Build Consistency",
    headingLarge: "Brand Identity",
    paragraph:
      "A complete visual identity designed to help your business look professional, build trust and stand out from competitors.",
    priceLarge: "£895",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Primary logo",
      "Secondary logo variations",
      "Logo icon",
      "Colour palette",
      "Typography selection",
      "Brand guidelines",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 7,
    service: "brand",
    headingSmall: "Go Further",
    headingLarge: "Brand System",
    paragraph:
      "For businesses looking to create a consistent brand experience across every customer touchpoint.",
    priceLarge: "£1495",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Everything in Brand Identity",
      "Extended brand guidelines",
      "Social templates",
      "Business card design",
      "Marketing assets",
      "Vehicle graphics concepts",
      "Additional brand applications",
    ],
    badge: false,
  },
];
