import { Pricing } from "@/types";

export const pricing: Pricing[] = [
  {
    id: 1,
    service: "web",
    headingSmall: "Launch Faster",
    headingLarge: "One Page Website",
    paragraph:
      "Perfect for new businesses, startups and local service providers looking to establish a professional online presence without the cost of a larger website.",
    priceLarge: "£495",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£24",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 2,
    service: "web",
    headingSmall: "Grow Online",
    headingLarge: "Multi-Page Website",
    paragraph:
      "Designed for businesses that mean business. Our multi-page websites provide the flexibility to showcase your services, build trust with potential customers and create a stronger foundation for long-term growth.",
    priceLarge: "£1250",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£40",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "2-6 pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 3,
    service: "web",
    headingSmall: "Scale Further",
    headingLarge: "Growth Website",
    paragraph:
      "Designed for businesses that need more content, more services, more locations & more room to grow. Ideal for established businesses looking to improve visibility, expand into new areas or create a stronger online presence.",
    priceLarge: "£2500",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£70",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "7+ pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 4,
    service: "web",
    headingSmall: "Build Authority",
    headingLarge: "Blog & Insights",
    paragraph:
      "Add a fully managed blog section to your website and publish content that helps build trust, improve search visibility and demonstrate your expertise over time.",
    priceLarge: "£30",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Why it matters",
    bulletList: [
      "Improves search visibility",
      "Builds trust with potential customers",
      "Demonstrates your expertise",
      "Targets valuable local search terms",
      "Supports long-term SEO growth",
    ],
    badge: true,
    badgeText: "Popular Upgrade",
  },
];
