import { Pricing } from "@/types";

export const pricing: Pricing[] = [
  {
    id: 1,
    service: "web",
    headingSmall: "Launch Faster",
    headingLarge: "One Page Website",
    paragraph:
      "Perfect for new businesses, startups and local service providers looking to establish a professional online presence without the cost of a larger website.",
    priceLarge: "£495",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£24",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 2,
    service: "web",
    headingSmall: "Grow Online",
    headingLarge: "Multi-Page Website",
    paragraph:
      "Ideal for growing businesses looking to showcase their services, build trust with potential customers and create a stronger online presence.",
    priceLarge: "£1250",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£40",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "2-6 pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 3,
    service: "web",
    headingSmall: "Scale Further",
    headingLarge: "Growth Website",
    paragraph:
      "Built for established businesses that need more content, more services, more locations and more room to grow online.",
    priceLarge: "£2500",
    priceSmall: "+ VAT",
    monthlyCarePlan: true,
    monthlyCarePlanPrice: "£70",
    bulletHeading: "Includes",
    bulletList: [
      "Bespoke website design",
      "7+ pages",
      "Built using NEXT.JS",
      "Mobile first design",
      "Contact form",
      "SEO setup",
      "Social media links",
      "Google maps intergration",
      "Fast loading performance",
      "Structured data",
      "Domain connection",
      "Google Search Console Setup",
    ],
    badge: false,
  },
  {
    id: 4,
    service: "web",
    headingSmall: "Build Authority",
    headingLarge: "Blog & Insights",
    paragraph:
      "Add a fully managed blog section to your website and publish content that helps build trust, improve search visibility and demonstrate your expertise over time.",
    priceLarge: "£30",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Why it matters",
    bulletList: [
      "Improves search visibility",
      "Builds trust with potential customers",
      "Demonstrates your expertise",
      "Targets valuable local search terms",
      "Supports long-term SEO growth",
    ],
    badge: true,
    badgeText: "Popular Upgrade",
  },
  {
    id: 5,
    service: "brand",
    headingSmall: "Get Recognised",
    headingLarge: "Logo Design",
    paragraph:
      "Perfect for new businesses looking for a professional logo that can be used across digital and print applications.",
    priceLarge: "£300",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Primary logo",
      "Logo icon / mark",
      "Light and dark versions",
      "PNG exports",
      "Vector artwork",
    ],
    badge: false,
  },
  {
    id: 6,
    service: "brand",
    headingSmall: "Build Consistency",
    headingLarge: "Brand Identity",
    paragraph:
      "A complete visual identity designed to help your business look professional, build trust and stand out from competitors.",
    priceLarge: "£895",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Primary logo",
      "Secondary logo variations",
      "Logo icon",
      "Colour palette",
      "Typography selection",
      "Brand guidelines",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 7,
    service: "brand",
    headingSmall: "Go Further",
    headingLarge: "Brand System",
    paragraph:
      "For businesses looking to create a consistent brand experience across every customer touchpoint.",
    priceLarge: "£1495",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Everything in Brand Identity",
      "Extended brand guidelines",
      "Social templates",
      "Business card design",
      "Marketing assets",
      "Vehicle graphics concepts",
      "Additional brand applications",
    ],
    badge: false,
  },
  {
    id: 8,
    service: "photo",
    headingSmall: "Capture Attention",
    headingLarge: "Photography",
    paragraph:
      "Professional photography designed to showcase your business, your people and the quality of your work. Perfect for businesses looking to replace stock imagery with authentic visuals that build trust online.",
    priceLarge: "£200",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Professional business photography",
      "Team and staff photography",
      "Social templates",
      "Project and portfolio photography",
      "Vehicle and equipment photography",
      "Website-ready image delivery",
      "Social media-ready image delivery",
    ],
    badge: false,
  },
  {
    id: 9,
    service: "photo",
    headingSmall: "Bring It To Life",
    headingLarge: "Photography + Video",
    paragraph:
      "Combine professional photography and video content to showcase your business across websites, social media and marketing campaigns. Ideal for businesses looking to create a stronger brand presence and connect with their audience.",
    priceLarge: "£600",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Professional photography",
      "Short-form video content",
      "Team and project imagery",
      "Website-ready assets",
      "Social media-ready content",
      "Multi-platform delivery",
    ],
    badge: false,
  },
  {
    id: 10,
    service: "photo",
    headingSmall: "Tell Your Story",
    headingLarge: "Event Videography",
    paragraph:
      "Professional video production designed to showcase your business, communicate what makes you different and bring your story to life. Perfect for businesses looking to engage customers and strengthen their online presence.",
    priceLarge: "£1200",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Discovery and planning",
      "On-location filming",
      "Professional editing",
      "Licensed music",
      "Colour grading",
      "Multiple export formats",
      "Website and social media delivery",
    ],
    badge: false,
  },
  {
    id: 11,
    service: "seo",
    headingSmall: "Get Found",
    headingLarge: "SEO Foundations",
    paragraph:
      "Perfect for businesses looking to improve visibility and ensure their website is built on strong SEO fundamentals.",
    priceLarge: "£250",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "SEO audit",
      "Keyword research",
      "Technical SEO review",
      "On-page recommendations",
      "Google Search Console setup",
      "Analytics setup",
    ],
    badge: false,
  },
  {
    id: 12,
    service: "seo",
    headingSmall: "Improve Visibility",
    headingLarge: "SEO Growth",
    paragraph:
      "Ongoing SEO support designed to improve rankings, increase visibility and generate more enquiries.",
    priceLarge: "£450",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Everything in SEO Foundations",
      "Ongoing optimisation",
      "Keyword tracking",
      "Content recommendations",
      "Local SEO improvements",
      "Monthly reporting",
    ],
    badge: true,
    badgeText: "Most Popular",
  },
  {
    id: 13,
    service: "seo",
    headingSmall: "Target New Areas",
    headingLarge: "SEO Expansion",
    paragraph:
      "Designed for businesses looking to increase visibility across multiple locations and service areas.",
    priceLarge: "£750",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Location research",
      "Additional landing pages",
      "Local keyword targeting",
      "Internal linking strategy",
      "Structured data implementation",
      "Google Business Profile optimisation",
    ],
    badge: false,
  },
  {
    id: 14,
    service: "graphic",
    headingSmall: "Create Assets",
    headingLarge: "Graphic Design",
    paragraph:
      "Professional design for businesses that need marketing materials, promotional graphics and day-to-day design support.",
    priceLarge: "£150",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Flyer design",
      "Poster design",
      "Social media graphics",
      "Advert artwork",
      "Business stationery",
      "Print-ready files",
    ],
    badge: false,
  },
  {
    id: 15,
    service: "graphic",
    headingSmall: "Promote Your Business",
    headingLarge: "Marketing Materials",
    paragraph:
      "Designed for businesses looking to create a consistent set of marketing assets that help build trust and support growth.",
    priceLarge: "£250",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Business card design",
      "Social media graphics",
      "Print-ready artwork",
      "Multiple design revisions",
      "Digital and print formats",
    ],
    badge: false,
  },
  {
    id: 16,
    service: "graphic",
    headingSmall: "Stand Out",
    headingLarge: "Custom Illustration",
    paragraph:
      "Bespoke illustrations and graphics created specifically for your business, helping you create a more distinctive and memorable brand presence.",
    priceLarge: "£500",
    priceSmall: "+ VAT",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Custom illustrations",
      "Character design",
      "Website graphics",
      "Social content graphics",
      "Marketing illustrations",
      "Digital asset delivery",
    ],
    badge: false,
  },
  {
    id: 17,
    service: "social",
    headingSmall: "Stay Visible",
    headingLarge: "Content Creation",
    paragraph:
      "Consistent content designed to keep your business visible, support your marketing efforts and help potential customers discover what you do.",
    priceLarge: "£150",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Content planning",
      "Social media graphics",
      "Caption writing",
      "Monthly content delivery",
    ],
    badge: false,
  },
  {
    id: 18,
    service: "social",
    headingSmall: "Build Trust",
    headingLarge: "Content & Design",
    paragraph:
      "Consistent content designed to keep your business visible, support your marketing efforts and help potential customers discover what you do.",
    priceLarge: "£300",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Content planning",
      "Graphic design",
      "Social media graphics",
      "Caption writing",
      "Monthly content delivery",
      "Content scheduling",
    ],
    badge: false,
  },
  {
    id: 19,
    service: "social",
    headingSmall: "Tell Your Story",
    headingLarge: "Content & Visuals",
    paragraph:
      "A complete content solution combining photography, video and design to showcase your business, strengthen your brand and create meaningful connections with your audience.",
    priceLarge: "£500",
    priceSmall: "+ VAT per month",
    monthlyCarePlan: false,
    bulletHeading: "Includes",
    bulletList: [
      "Content planning",
      "Photography integration",
      "Video content integration",
      "Graphic design",
      "Content creation",
      "Scheduling support",
      "Performance review",
    ],
    badge: false,
  },
];
